
  
<nav class="navbar navbar-toggleable-md navbar-light bg-white sticky-top mediumnavigation">

    <div class="container">
        <a href="/" class="navbar-brand ms-5 px-5">
            <i class="fa-solid fa-book"></i>
            <span class=" ms-2 fw-bold fs-3">The</span><span class=" fw-normal fs-3">Bloggers</span>
        </a>
        <a class="nav-link text-dark" href="/dashboard">
            Dashboard
        </a>
        <a href="/login">
            <button class="btn btn-dark rounded authButton">Sign In</button>
        </a>
    </div>
</nav>